"$schema" = "./didm.schema.json"
[sketch.kvan-qt]
override_behaviour.overwrite_existed = true
override_behaviour.backup_existed = false
source_path = "./qt"
target_path = "$DIDM_TARGET_HOME/.config"
mode = "copy"
