"$schema" = "./didm.schema.json"
[sketch.gui-config]
source_path = "./config/"
target_path = "$DIDM_TARGET_HOME/.config"
ignore = ["kitty/themes"]
mode = "symlink"
extra_entries = [
	{ source_path = "kitty/themes/Catppuccin-Mocha.conf", target_path = "kitty/current_theme.conf", mode = "symlink" },
	{ source_path = "hypr/lib/GPU/1Default.conf", target_path = "hypr/configs/GPU.conf", mode = "symlink" },
	{ source_path = "hypr/lib/Monitor/1Default.conf", target_path = "hypr/configs/Monitors.conf", mode = "symlink" },
	{ source_path = "/dev/null", target_path = "hypr/configs/Shader.conf", mode = "symlink" },
	{ source_path = "waybar/configs/1Lapoch.jsonc", target_path = "waybar/config", mode = "symlink" },
	{ source_path = "waybar/style/Catcha.css", target_path = "waybar/style.css", mode = "symlink" },
]
[sketch.gui-local]
source_path = "./local"
target_path = "$DIDM_TARGET_HOME/.local"
mode = "copy"
[sketch.gui-home]
source_path = "./user"
target_path = "$DIDM_TARGET_HOME"
